spring:
 mvc:
    hiddenmethod:
      filter:
        enabled: true
 servlet:
   multipart:
     max-file-size: 20MB
     max-request-size: 20MB
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wawt
    username: wawt
    password: 49895963
image:
  local: true