spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wawt
    username: wawt
    password: password

  h2:
    console:
      enabled: true
      debug: true

  image:
   local: true